<?xml version="1.0"?>
<robot name="Diff_H80" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PARKING_ROBOT_SACLE" value="0.001" />
  <xacro:property name="GROUND_CLEARANCE" value="0.131231" />

  <xacro:include filename="$(find Diff_H80_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find Diff_H80_description)/urdf/Diff_H80.trans" />
  <xacro:include filename="$(find Diff_H80_description)/urdf/Diff_H80.gazebo" />

  <link name="dummy_link" />

  <link name="base_link">
    <inertial>
      <origin xyz="-0.011449016469047966 0.01315775461098758 0.15791582518187486" rpy="0 0 0" />
      <mass value="9.393259852945702" />
      <inertia ixx="0.371683" iyy="0.220355" izz="0.422433" ixy="-0.001416" iyz="0.008743" ixz="0.000944" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${GROUND_CLEARANCE}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://Diff_H80_description/meshes/base_link.stl"
          scale="${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE}" />
      </geometry>
      <material name="silver" />
    </visual>
    <collision>
      <origin xyz="0 0 ${GROUND_CLEARANCE}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://Diff_H80_description/meshes/base_link.stl"
          scale="${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE}" />
      </geometry>
    </collision>
  </link>

  <link name="wheel_1">
    <inertial>
      <origin xyz="0.052673866816185244 -1.1762068571896656e-07 2.967117346264203e-07" rpy="0 0 0" />
      <mass value="2.9857823803068295" />
      <inertia ixx="0.028562" iyy="0.015662" izz="0.015726" ixy="-0.0" iyz="-0.0" ixz="0.0" />
    </inertial>
    <visual>
      <origin xyz="0.188674 0.197557 ${GROUND_CLEARANCE - 0.131231}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://Diff_H80_description/meshes/wheel_1.stl"
          scale="${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE}" />
      </geometry>
      <material name="silver" />
    </visual>
    <collision>
      <origin xyz="0.188674 0.197557 ${GROUND_CLEARANCE - 0.131231}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://Diff_H80_description/meshes/wheel_1.stl"
          scale="${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE}" />
      </geometry>
    </collision>
  </link>

  <link name="wheel_2">
    <inertial>
      <origin xyz="0.05267386681617087 -1.1762068591325558e-07 2.967117369023775e-07" rpy="0 0 0" />
      <mass value="2.9857823803068295" />
      <inertia ixx="0.028562" iyy="0.015662" izz="0.015726" ixy="-0.0" iyz="-0.0" ixz="0.0" />
    </inertial>
    <visual>
      <origin xyz="-0.188674 0.202443 ${GROUND_CLEARANCE - 0.131231}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://Diff_H80_description/meshes/wheel_2.stl"
          scale="${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE}" />
      </geometry>
      <material name="silver" />
    </visual>
    <collision>
      <origin xyz="-0.188674 0.202443 ${GROUND_CLEARANCE -0.131231}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://Diff_H80_description/meshes/wheel_2.stl"
          scale="${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE}" />
      </geometry>
    </collision>
  </link>

  <link name="wheel_3">
    <inertial>
      <origin xyz="-0.05267356462253964 -1.1762070392662416e-07 2.509659630389738e-07" rpy="0 0 0" />
      <mass value="2.9857823803068295" />
      <inertia ixx="0.028562" iyy="0.015662" izz="0.015726" ixy="0.0" iyz="0.0" ixz="0.0" />
    </inertial>
    <visual>
      <origin xyz="0.211326 -0.197557 ${GROUND_CLEARANCE -0.131231}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://Diff_H80_description/meshes/wheel_3.stl"
          scale="${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE}" />
      </geometry>
      <material name="silver" />
    </visual>
    <collision>
      <origin xyz="0.211326 -0.197557 ${GROUND_CLEARANCE - 0.131231}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://Diff_H80_description/meshes/wheel_3.stl"
          scale="${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE}" />
      </geometry>
    </collision>
  </link>

  <link name="wheel_4">
    <inertial>
      <origin xyz="-0.05267356462255357 -1.1762070406540204e-07 2.5096596523166426e-07" rpy="0 0 0" />
      <mass value="2.9857823803068295" />
      <inertia ixx="0.028562" iyy="0.015662" izz="0.015726" ixy="0.0" iyz="0.0" ixz="0.0" />
    </inertial>
    <visual>
      <origin xyz="-0.211326 -0.202443 ${GROUND_CLEARANCE -0.131231}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://Diff_H80_description/meshes/wheel_4.stl"
          scale="${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE}" />
      </geometry>
      <material name="silver" />
    </visual>
    <collision>
      <origin xyz="-0.211326 -0.202443 ${GROUND_CLEARANCE -0.131231}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://Diff_H80_description/meshes/wheel_4.stl"
          scale="${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE} ${PARKING_ROBOT_SACLE}" />
      </geometry>
    </collision>
  </link>

  <joint name="dummy_joint" type="fixed">
    <parent link="dummy_link" />
    <child link="base_link" />
  </joint>

  <joint name="rear_right" type="continuous">
    <origin xyz="-0.188674 -0.197557 0.131231" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_1" />
    <axis xyz="-0.0 -1.0 -0.0" />
  </joint>

  <joint name="front_right" type="continuous">
    <origin xyz="0.188674 -0.202443 0.131231" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_2" />
    <axis xyz="-0.0 -1.0 -0.0" />
  </joint>

  <joint name="rear_left" type="continuous">
    <origin xyz="-0.211326 0.197557 0.131231" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_3" />
    <axis xyz="0.0 1.0 0.0" />
  </joint>

  <joint name="front_left" type="continuous">
    <origin xyz="0.211326 0.202443 0.131231" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_4" />
    <axis xyz="0.0 1.0 0.0" />
  </joint>

</robot>